### ISSUE TITLE
Optical Floor Tracking System

### ISSUE THREAD

**Issue by UltraX3** [Team-2502/RobotCode2018#26]
I think it could possibly be helpful to have an optical floor tracking system for telling the velocity of the robot. This could replace/complement the accelerometer in situations where the robot slides. Unlike tracking the ceiling, tracking the floor might not yield the best absolute positions as it becomes more off as time progresses.

This has been used in real life in the [Scarab Lunar Rover](http://www.frc.ri.cmu.edu/project/lri/scarab/components/velocityCamera/velocityCamera.html) and is a problem in the domain of [Optical Flow](https://en.wikipedia.org/wiki/Optical_flow). The paper [Optical Flow Estimation](http://www.cs.toronto.edu/~fleet/research/Papers/flowChapter05.pdf)  seems to explain it well so far (from what I see). Additionally someone in FRC has [done this before with a mouse](https://www.youtube.com/watch?v=Aup6CQv_-j4). 

What are your thoughts?

**Comment by ritikmishra** [comment]
I think the floor would be more realistic than ceiling tracking (#22) , especially since it has been done before.
