### ISSUE TITLE
Left encoder not functioning properly

### ISSUE THREAD

**Issue by UltraX3** [Team-2502/RobotCode2018#27]
When logging the changes in left encoder values, the returned value is consistently `0`. This is strange, because I am almost sure it was working on 2018/01/12 (Fri).

- [x] Checked encoder is green
- [x] Checked connected to right talon

**Comment by isaacaj** [comment]
Fixed issue by completely remapping the drivetrain motors to the correct talons. ID's are now the same as in code, and left/right encoders go to the right left/right motors.
