### ISSUE TITLE
Pure Pursuit needs to use Skid Steer formulas

### ISSUE THREAD

**Issue by UltraX3** [Team-2502/RobotCode2018#30]

**Comment by ritikmishra** [comment]
Pure Pursuit seems to be good enough as it is, closed.

**Comment by UltraX3** [comment]
@ritikmishra "the skid steer formulas" is just variable lateral wheel distance for given speeds.

**Comment by ritikmishra** [comment]
Then it's a duplicate of #42 titled "Variable lateral wheel distance"

**Comment by UltraX3** [comment]
I see. Closed.
