### ISSUE TITLE
Make Pure Pursuit Widget

### ISSUE THREAD

**Issue by UltraX3** [Team-2502/RobotCode2018#37]
Requires drawing:
- Robot (quadrilateral) with a given `(x,y,heading)`
- Circle `(x,y,r)`
- Line `(x,y,z)`

You will need to draw similar to [my simulation](https://github.com/UltraX3/PurePursuit), but it will use real sensor data.

**Comment by ritikmishra** [comment]
Tip: https://github.com/wpilibsuite/shuffleboard/wiki/Plugins

**Comment by UltraX3** [comment]
Quite hard. Not enough benefit to implement at this point.
