### ISSUE TITLE
PIDs are strange

### ISSUE THREAD

**Issue by UltraX3** [Team-2502/RobotCode2018#38]
When using PID for tuning wheel velocity, the velocities always oscillate at a value too small. For example, at the target speed of 1 RPM, the wheels actually go at ~.75 RPM (this proportion is not constant at different speeds).

**Comment by ritikmishra** [comment]
Solution: Tune your PID better. You can call in a PID expert (Isaac A.) or use the Ziegler-Nichols method of tuning PID.

**Comment by UltraX3** [comment]
Basically, if there are _oscillations_ around a certain value that is not the target, that means something is really weird.

**Comment by UltraX3** [comment]
Fixed
