### ISSUE TITLE
PID tuning does not work for left motors

### ISSUE THREAD

**Issue by UltraX3** [Team-2502/RobotCode2018#39]
PID tuning does not work for left drive train motors (it does for right). This is almost surely because the left talons are reversed. Even when the left motors are set to inverted, the proportional error still grows when getting closer and closer to the target velocity. This makes it seem like talon is thinking the motor is getting further (going in the opposite direction) from desired when actually getting closer.

**Comment by ritikmishra** [comment]
On herschel, one side still uses a quadrature encoder, whilst the other uses CTRE mag encoders. I do not remember which, but you can take a peek when the robot bottom is visible while it is on the cart.

**Comment by UltraX3** [comment]
As of a ~week ago both now use CTRE mag encoders :)

**Comment by UltraX3** [comment]
This needs to work soon for pure pursuit since `voltage ratios != wheel speed ratios`, and pure pursuit relies on these ratios to function.

**Comment by UltraX3** [comment]
Update: Michael thinks he inverted the right talons, but it seems like both sides are now inverted. Can some programmer verify this?

**Comment by UltraX3** [comment]
Fixed after @MDW01 changed some things w/ electronics.
