### ISSUE TITLE
Use accelerometer data for localization when robot is detected to be slipping (more than usual)

### ISSUE THREAD

**Issue by UltraX3** [Team-2502/RobotCode2018#46]

**Comment by ritikmishra** [comment]
Even with the a working NavX, the accelerometer is pretty "noisy". This noise is amplified when the double integral is taken, so I doubt that the accelerometer data will be accurate to any degree

**Comment by UltraX3** [comment]
accelerometer is bad

**Comment by ritikmishra** [comment]
also how do you detect robot slippage

sounds like the proper solution is to forego using encoders for localization and instead attach a mouse to the bottom of the robot for localization.

**Comment by andrewgazelka** [comment]
slippage would be detected when the calculated position per a unit time is significantly different between the accelerometer and the encoders. I think a mouse sounds like a good idea to try.
