### ISSUE TITLE
Be able to set waypoint headings and velocities

### ISSUE THREAD

**Issue by andrewgazelka** [Team-2502/RobotCode2018#47]

**Comment by ritikmishra** [comment]
I think that the angle can be best achieved with the use of intermediate waypoints

**Comment by UltraX3** [comment]
@ritikmishra I agree that intermediate waypoints should _help_ determine heading, and maybe a modified Pure Pursuit would determine velocity at a certain period. However, when picking up cubes I am thinking we will need a specific heading (and lowered velocity). Maybe we can combine Pure Pursuit with some more basic trajectory alg when we get very close to the destination?

**Comment by UltraX3** [comment]
what probably makes more sense is being able to set max velocities between waypoints

**Comment by ritikmishra** [comment]
Perhaps we can fix theta in splines where we can set the derivative at a control point
(speed works)

**Comment by andrewgazelka** [comment]
If this were added, it would be with splines.

**Comment by ritikmishra** [comment]
Alright, I've figured out how to make parametric cubic splines. Hopefully this will be fixed soon

**Comment by andrewgazelka** [comment]
Yay. 👍 let's close this after we do unit tests in the simulator.

**Comment by ritikmishra** [comment]
Unit tests on splines have been completed in the simulator and are quite successful.

🎉
