### ISSUE TITLE
Fix using purely encoders for localization being bad

### ISSUE THREAD

**Issue by andrewgazelka** [Team-2502/RobotCode2018#66]

**Comment by ritikmishra** [comment]
How are the encoders "bad"?

What other sensor do you propose using for localization?

* NavX Accelerometer
    * Unreliable, noisy
* LIDAR
    * Unimplemented, i don't think we even have one

**Comment by andrewgazelka** [comment]
Probably fixed (since it works in the simulator). We will need to test on a robot first, though.
